=== Mosh333/Web-Development/TMA_1/part1/part1.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="resume">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Name" type="xs:string" />
        <xs:element name="Highlights">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="description_1" type="xs:string" />
              <xs:element name="description_2" type="xs:string" />
              <xs:element name="description_3" type="xs:string" />
              <xs:element name="description_4" type="xs:string" />
              <xs:element name="description_5" type="xs:string" />
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="Education">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="degree">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="degree_info1" type="xs:string" />
                    <xs:element name="degree_info2" type="xs:string" />
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="Skills">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="skills1" type="xs:string" />
              <xs:element name="skills2" type="xs:string" />
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="Work_Experience">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="job1">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="title" type="xs:string" />
                    <xs:element name="responsibility1" type="xs:string" />
                    <xs:element name="responsibility2" type="xs:string" />
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== Mosh333/Web-Development/TMA_1/part1/part1.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="part1.xsl"?>
<resume
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="part1.xsd"
>
<Name> 
    Moshiur Howlader
</Name>
<Highlights>
    <description_1>
        •	Final Year McMaster Computer Engineering Student. 
   </description_1>
   <description_2>
        •	Proficient with both Software and Hardware.
   </description_2>
   <description_3>
        •	Experience with various programming languages.
   </description_3>
   <description_4>
        •	Strong Foundations in Computer Science/Engineering. Core competency in Electrical Engineering.
   </description_4>
   <description_5>
        •	Looking to become a Software or Computer Engineer in a reputable tech company after graduation.
   </description_5>
</Highlights>

<Education>
    <degree> 
        <degree_info1>•	Bachelor of Engineering in Computer Engineering w/ Co-Op (B. Eng)</degree_info1>
        <degree_info2>Class of 2019 McMaster University, Hamilton, ON (expected)</degree_info2>
    </degree>
</Education>

<Skills>
    <skills1>•	Python, HTML, CSS, JavaScript, Matlab/Simulink, Assembly, Linux, Unix, SQL, Wireshark, Version Control (GIT), (System)Verilog/VDHL, C, and Java</skills1>
    <skills2>•	Computer Architecture, Networks, Digital System Design, Microprocessor, Embedded System, Hardware-Software interfacing, Image Processing, OS, and Software Development</skills2>
</Skills>

<Work_Experience>
    <job1>
        <title>Application Analyst – CIBC, Toronto, ON - [Sept 2016 – April 2017]</title>
        <responsibility1>•	Assisted CIBC Developers to develop, maintain, document, and assist in trouble shooting various financial application systems (Siebel - internal client database management software)</responsibility1>
        <responsibility2>•	Manage Incident, Change Management tickets, and other miscellaneous tasks (Unix, SQL)</responsibility2>
    </job1>
</Work_Experience>

</resume>
